version: "3.7"

services:
  dev-fast-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 17301 --reload
    ports:
      - 27080:17301
    volumes:
      - ../app:/code/app
    networks:
      - cloud_api
  mysql-8:
    image: mysql:8.0
    restart: always
    container_name: mysql-8
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${MYSQL_DATA_DIRECTORY}:/var/lib/mysql
    networks:
      - cloud_api
  oracle-18c:
    image: pvargacl/oracle-xe-18.4.0
    container_name: oracle-18c
    restart: always
    ports:
      - ${ORACLE_PORT1}:1521
      - ${ORACLE_PORT2}:5500
    volumes:
      - ${ORACLE_DATA_DIRECTORY}:/opt/oracle/oradata
    environment:
      - ORACLE_SID=${ORACLE_ROOT_UID}
      - ORACLE_PWD=${ORACLE_ROOT_PASSWORD}
      - ORACLE_CHARACTERSET=AL32UTF8
    networks:
      - cloud_api
networks:
  cloud_api:
     driver: bridge
