version: "3.7"

services:
  moong_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 17080 --reload
    ports:
      - 80:17301
    volumes:
      - ../app:/code/app
    networks:
      - moong_project_net
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    ports:
      - "3306:17305"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${MYSQL_DATA_DIRECTORY}:/var/lib/mysql
    networks:
      - moong_project_net
networks:
  moong_project_net:
    driver: bridge